name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Build binaries for multiple OS and architectures
      run: |
        mkdir -p bin
        GOOS=linux GOARCH=amd64 go build -o bin/chap-linux-amd64
        GOOS=linux GOARCH=arm64 go build -o bin/chap-linux-arm64
        GOOS=darwin GOARCH=amd64 go build -o bin/chap-darwin-amd64
        GOOS=darwin GOARCH=arm64 go build -o bin/chap-darwin-arm64
        GOOS=freebsd GOARCH=amd64 go build -o bin/chap-freebsd-amd64

    - name: Upload binaries as artifacts
      uses: actions/upload-artifact@v3
      with:
        name: chap-binaries
        path: bin/*

  release:
    needs: build
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Download binary artifacts
      uses: actions/download-artifact@v3
      with:
        name: chap-binaries

    - name: Create or Update Release
      id: create_release
      run: |
        gh release view latest || gh release create latest ./bin/* --title "latest" --notes "Latest release"
        gh release upload latest ./bin/*

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
